-- DEPRECATED: 이 마이그레이션은 하드코드 anon JWT 문제로 인해 비활성화되었습니다.
-- 대체 마이그레이션: 20260410_cron_schedules_secure.sql
--
-- 새 마이그레이션은 Supabase Vault(vault.secrets)에서 'cron_auth_token',
-- 'functions_base_url' 시크릿을 읽어서 cron 작업을 생성합니다.
-- fresh 환경에서는 아래 두 시크릿을 먼저 등록해야 합니다:
--   SELECT vault.create_secret('<anon jwt>', 'cron_auth_token');
--   SELECT vault.create_secret('https://<project>.supabase.co/functions/v1', 'functions_base_url');
--
-- no-op
SELECT 1;
